# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Some amazhang thoughts
email: anthony@amazhang.com
description: > # this means to ignore newlines until "baseurl:"
  This is the blog of the New York based designer, Anthony Zhang.
  The site is to serve as a test drive for messing with Jekyll and
  seeing if I can actually keep to updating a blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amazhang.com" # the base hostname & protocol for your site
twitter_username: amazhang
github_username:  amazhang

# Build settings
markdown: kramdown
